# Site
repository: sidrocks123/sidrocks123.github.io
# favicon: images/favicon.ico

# Personal info
name: Siddhartha Khanooja
title: Software Engineer
email: siddhartha.khanooja@gmail.com
website: https://sidrocks123.github.io

# Social links
twitter_username: sidkhanooja
github_username:  sidrocks123
# dribbble_username: jekyll
facebook_username: SidKhanooja
# flickr_username: jekyll
instagram_username: sidkhanooja
linkedin_username: siddharthakhanooja
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Siddhartha and I'm a Software Engineer working at HSBC, Hyderabad. I am currently working in the Cards Engineering Division, and have worn both development and testing hats. 
  
  Having gained an ample amount of experience with CS from both my Bachelors degree and my work in industry, I am now aspiring for my Masters Degree in CS, to further my theoretical foundation and work with reputed companies located not just in India, but around the globe. I feel that a Masters degree will open a lot of doors faster than I would achieve with just my experience. 

  I am most skilled in: <mark>Python</mark>, <mark>JavaScript</mark>, <mark>COBOL</mark>, and <mark>Selenium</mark>.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests of software engineering, some of my other interests and hobbies are:
   - Running and cycling
   - Singing
   - Writing
   - Debating

# Footer
footer_show_references: true

# Build settings
remote_theme: sidrocks123/sidrocks123.github.io

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

theme: jekyll-theme-minimal
